apiVersion: v1
kind: Namespace
metadata:
  name: gitea
  labels:
    name: gitea
---
apiVersion: v1
kind: Namespace
metadata:
  name: taiga
  labels:
    name: taiga
---
apiVersion: v1
kind: Namespace
metadata:
  name: agents
  labels:
    name: agents
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    name: registry
