apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: taiga-db
  namespace: taiga
spec:
  serviceName: taiga-db
  replicas: 1
  selector:
    matchLabels:
      app: taiga-db
  template:
    metadata:
      labels:
        app: taiga-db
    spec:
      containers:
        - name: postgres
          image: postgres:12.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taiga-secret
                  key: postgres-password
          volumeMounts:
            - name: taiga-db-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - taiga
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - taiga
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: taiga-db-data
          persistentVolumeClaim:
            claimName: taiga-db-data

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-db
  namespace: taiga
spec:
  selector:
    app: taiga-db
  ports:
    - port: 5432
      targetPort: 5432
